### ISSUE TITLE
Non-divisible-by-4 buffer sizes seem to cause a crash now

### ISSUE THREAD

**Issue by AsuMagic** [jarikomppa/soloud#251] opened 2020-02-27 12:13 UTC
> Actual behavior:

Playing any audio seems to cause a crash within `panAndExpand` if you have an non-divisible-by-4 buffer size.

> Steps to reproduce the problem:

Somehow make it so you have a non-divisible-by-4 buffer size and play audio (tested with `Wav`/`WavStream`). This at least reproduces on the SDL2 static backend.

> SoLoud version, operating system, backend used, any other potentially useful information:

Built against `master` (commit: https://github.com/jarikomppa/soloud/commit/c65132a6af2c095c47b1cc2f0d807f544dc59941)

https://github.com/jarikomppa/soloud/commit/c65132a6af2c095c47b1cc2f0d807f544dc59941 is the likely culprit.

The following environments do **NOT** reproduce the crash:

- Linux 64-bit, SDL2 dynamic, 2048 buffer size
- MinGW 64-bit through Wine, SDL2 static, 132 buffer size

The following environments **DO** reproduce the crash:

- MinGW 64-bit on native Windows (not on my system), SDL2 static, **981** buffer size

The person who can reproduce the crash only had a build of my software with limited debug symbols. If you are unable to reproduce the crash with just that I can try to extract more info and investigate further on my end.

I'm not sure how to affect buffer size on my own machine so I couldn't reproduce it myself.

**Comment by jarikomppa** [comment] 2020-02-27 13:10
Well crap. The crash shouldn't have anything to do with the buffer size, but alignment. I should put asserts there to make sure they're aligned. They should be, as the inputs to the function should all be soloud-internal, instead of coming from outside. If convenient, what do the aBuffer and aScratch pointers look like?

**Comment by jarikomppa** [comment] 2020-02-27 13:30
Added the asserts.

The panAndExpand does 4 samples at a time for the divisible-by-4 portion of the input buffer, and then one sample at a time for any leftovers. The most likely culprit is that somehow, a non-aligned buffer gets used as input or output, but that shouldn't be the case.

panAndExpand is called from mixBus_internal which is called from two places: busses and the main mixer. For the main mixer, the output goes to mOutputScratch which is an aligned buffer, and scratch is class soloud's mScratch, whichis an aligned buffer.

For busses, output goes to resampleData, which is doled out of mResampleDataBuffer which again is an aligned buffer, and scratch is busses' mScratch which is an aligned buffer.

**Comment by AsuMagic** [comment] 2020-02-27 14:57
I tried again with the asserts, neither of them triggered. I sent a build with full debug symbols to the guy who got the crash, some stuff got optimized away though (ironically I have to fix a bug in my codebase where it will link only when LTO is on).

Here's a link to the logs of the crash that were sent to me: https://pastebin.com/z3nDz0vB  
Scroll down to see the gdb backtrace. For some reason Github won't let me comment if I copy it here.

**Comment by jarikomppa** [comment] 2020-02-27 15:34
aBuffer=0x13107fb0 looks fine
aScratch=<optimized out> !?!, probably inlined or something
The fact it optimizes out the sse temp variables doesn't surprise me at all (and is fine).

Crash seems to happen at /usr/lib/gcc/x86_64-w64-mingw32/9.2.1/include/xmmintrin.h:198, which again points at the alignment stuff. If I happen to have found the exact same header, it looks like _mm_mul_ps() call, which, again, points at the alignment stuff.

**Comment by AsuMagic** [comment] 2020-02-27 15:55
I checked the header and I can confirm it is the `_mm_mul_ps()` call.

**Comment by jarikomppa** [comment] 2020-02-27 16:44
That may well be the first actual sse call.

**Comment by jarikomppa** [comment] 2020-02-27 16:54
To rule things out, it might be useful to know what cpu the pc has that shows the problem. It's possible that the ryzen7 that I have is more relaxed about alignment things, for example.

**Comment by AsuMagic** [comment] 2020-02-27 17:50
The machine on which this crashes is a Ryzen 5 2600 (native windows x64).  
I cannot reproduce it on my Ryzen 9 3900X (linux w/wine) or my laptop's Core2 T9600 (linux w/ wine).

So it is probably not related to architectural differences.

I'm not sure I understood properly what you said earlier, do you think it is related to the non-divisible-by-4 buffer size or not? Is there any way to force a buffer size so that I can rule this out?

**Comment by jarikomppa** [comment] 2020-02-27 18:13
The crash seems to occur in an SSE instruction, and one that doesn't even read from memory but uses two registers. I presume this is inaccuracy on the debug info in release mode, because that makes no sense, and it's actually a memory read that's failing. Or, possibly, memory write.

In addition, SIGSEGV usually means memory access failure. ... nevermind, checked, apparently the alignment issues also cause SIGSEGV.

You can just comment out the block that says // If buffer size or samples to read are not divisible by 4... to rule out the not-divisible-by-4 case. I've used backends with such buffer sizes without issues, though.

**Comment by jarikomppa** [comment] 2020-02-27 18:21
samplequads is 245, 245 * 4 = 980. 
aBufferSize is 981. That means there's one left over for the follow-up loop.

Oh crap. I just realized what the issue is.

We're reading from (aScratch + c + aBufferSize). Since aBufferSize isn't divisible by 4, it breaks.

**Comment by jarikomppa** [comment] 2020-02-27 18:27
The proper fix will be to make the buffer stride divisible by 4, but that requires bigger changes and more thought. I've pushed a fix that simply skips the SSE for buffers that are not divisible by 4.

**Comment by jarikomppa** [comment] 2020-02-27 18:27
Sorry for the inconvenience.

**Comment by AsuMagic** [comment] 2020-02-27 18:30
No problem, glad I could help!

**Comment by jarikomppa** [comment] 2020-02-27 18:31
Also, I have no idea why it doesn't break on my system. Have to see if it blows up on a corei5. Anyway, thanks.

**Closed by jarikomppa** 2020-02-27 18:31 UTC

**Comment by jarikomppa** [comment] 2020-02-27 19:07
Can't crash on a corei5 either, even when I misalign on purpose. Sigh. I guess I'll have to make the fix blind.

**Comment by AsuMagic** [comment] 2020-02-27 20:16
I can confirm that the latest workaround https://github.com/jarikomppa/soloud/commit/881ac9725b5a329d46973bf2a3d7867054f3dc34 fixes the issue

**Comment by jarikomppa** [comment] 2020-02-27 20:23
okay, just pushed a new version that should enable the sse again AND have everything aligned.. again. Rather large change, so something may have blown up, but it would be nice to know if it fixes this particular issue.

**Comment by jarikomppa** [comment] 2020-02-28 09:56
Further investigation suggests this shouldn't happen. Doesn't that make everybody feel better.

Alignment check should be off by default on x64 systems and misaligments should be handled by the operating system on x86 systems. Enabling the check should only be possible through a privledged cpu register bit, and even if you do manage to do it, it should break standard libraries (i.e, reading integers off unaligned addresses, so stuff like memcpy would likely break).

What I'm guessing is that mingw/gcc is more strict about alignment than, say, visual studio, and has libraries that are written to work with aligned memory only. Not completely far fetched considering platforms like ARM require (or used to) everything to be aligned. This then doesn't go through on all systems because of the privilege requirement, but some drivers or something may let applications do it, which would explain the randomness.

In the end it's best to have everything aligned for cache coherency, if nothing else, but it would be nice to be able to check that everything is aligned.. anyway, I'm done with my research for now unless something new pops up.

**Comment by AsuMagic** [comment] 2020-02-28 09:59
https://github.com/jarikomppa/soloud/commit/feb7b672608a067424e2e74d7f9af87e3e7d347b seems to have fixed the issue.

**Comment by jarikomppa** [comment] 2020-02-28 10:03
Thanks!
